services:
  # Backend Service
  - type: web
    name: edubridge-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false  # You'll set this manually
      - key: GEMINI_MODEL
        value: gemini-2.0-flash-exp
      - key: PORT
        value: 10000
    healthCheckPath: /api/gamify/paths

  # Frontend Service
  - type: web
    name: edubridge-frontend
    env: static
    plan: free
    buildCommand: cd apps/web && npm install && npm run build
    staticPublishPath: apps/web/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: edubridge-backend
          property: host
