# Render Blueprint for EduBridge (Docker Deployment)
# Documentation: https://render.com/docs/docker

services:
  - type: web
    name: edubridge
    env: docker
    plan: free
    region: oregon  # Choose the region closest to your users
    
    # Docker configuration
    dockerContext: .
    dockerfile: Dockerfile
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: VITE_API_URL
        value: /api  # API requests will be proxied through the same domain
    
    healthCheckPath: /api/ping
    autoDeploy: true
        value: https://edubridge-backend.onrender.com  # Update with your backend URL
    autoDeploy: true
