# Render Blueprint for EduBridge (Combined Frontend + Backend)
# Documentation: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: edubridge
    env: node
    plan: free
    region: oregon  # Choose the region closest to your users
    buildCommand: |
      # Install root dependencies
      cd /opt/render/project/src
      npm install
      
      # Install and build frontend
      cd /opt/render/project/src/apps/web
      npm install
      npm install -D vite@latest
      npm run build
      
      # Create public directory and copy frontend build
      mkdir -p /opt/render/project/src/server/public
      cp -r /opt/render/project/src/apps/web/dist/* /opt/render/project/src/server/public/
      
      # Install server dependencies
      cd /opt/render/project/src/server
      npm install
    
    startCommand: cd /opt/render/project/src/server && node server.js
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: VITE_API_URL
        value: /api  # API requests will be proxied through the same domain
    
    healthCheckPath: /api/ping
    autoDeploy: true
        value: https://edubridge-backend.onrender.com  # Update with your backend URL
    autoDeploy: true
